name: nia_flutter
description: "Nia Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_native_splash: ^2.3.9
  easy_localization: ^3.0.3
  firebase_crashlytics: ^3.4.8
  firebase_auth: ^4.6.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  firebase_analytics: ^10.7.4
  flutter_svg: ^2.0.9
  http: ^1.1.2
  path_provider: ^2.1.1
  web_socket_channel: ^2.4.0
  logger: ^2.0.2+1
  record: ^5.0.4
  just_audio: ^0.9.36
  image_picker: ^0.8.0+4
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  chat_bubbles: ^1.5.0
  loading_animation_widget: ^1.2.0+4
  flutter_facebook_auth: ^6.0.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/social_icons/
    - assets/images/onboardings/onboarding1.png
    - assets/images/onboardings/onboarding2.png
    - assets/images/onboardings/onboarding3.png
    - assets/images/logo/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo/nia.png"
  android: true
  ios: truet
  android_12:
    color: "#FFFFFF"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/nia.png"